[project]
name = "krita_plugin"
version = "1.0.0"
description = "Add your description here"
authors = [
    { name = "Pauan", email = "pauanyu+github@pm.me" }
]
requires-python = ">=3.13"
dependencies = [
    "desktop-notifier>=6.2.0",
    "numpy>=2.4.4",
    "pillow>=12.3.0",
    "qimage2ndarray>=1.10.0",
    "simpleeval>=1.0.7",
]

[dependency-groups]
local = [
    "shared",
]

[tool.uv.sources]
shared = { workspace = true, editable = true }

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "krita_comfyui"
#module-root = "krita"

