from enum import Enum
from typing import Any
from PyQt6.QtCore import QObject, pyqtBoundSignal
from PyQt6.QtWidgets import QDockWidget, QWidget

class Canvas(QObject): ...

class Window(QObject): ...

class Notifier(QObject):
    applicationClosing: pyqtBoundSignal
    def setActive(self, value: bool) -> None: ...

class Krita(QObject):
    @staticmethod
    def instance() -> Krita: ...
    def addExtension(self, extension: Extension) -> None: ...
    def addDockWidgetFactory(self, factory: DockWidgetFactoryBase) -> None: ...
    def notifier(self) -> Notifier: ...

class Extension(QObject):
    def __init__(self, parent: QObject | None = None) -> None: ...
    def setup(self) -> None: ...
    def createActions(self, window: Window) -> None: ...

class DockWidget(QDockWidget):
    def __init__(self) -> None: ...
    def canvasChanged(self, canvas: Canvas) -> None: ...

class DockWidgetFactoryBase:
    class DockPosition(Enum):
        DockNone = ...
        DockTornOff = ...
        DockTop = ...
        DockBottom = ...
        DockRight = ...
        DockLeft = ...
        DockMinimized = ...

class DockWidgetFactory(DockWidgetFactoryBase):
    def __init__(self, id: str, position: DockWidgetFactoryBase.DockPosition, dockWidgetClass: type[QWidget]) -> None: ...

def __getattr__(name: str) -> Any: ...
