from enum import Enum
from typing import Any
from PyQt6.QtCore import QObject
from PyQt6.QtWidgets import QDockWidget, QWidget

class Extension(QObject):
    def __init__(self, parent: QObject | None = None) -> None: ...
    def setup(self) -> None: ...
    def createActions(self, window: Any) -> None: ...

class DockWidget(QDockWidget):
    def __init__(self) -> None: ...
    def canvasChanged(self, canvas: Any) -> None: ...

class DockWidgetFactoryBase:
    class DockPosition(Enum):
        DockNone = ...
        DockTornOff = ...
        DockTop = ...
        DockBottom = ...
        DockRight = ...
        DockLeft = ...
        DockMinimized = ...

class DockWidgetFactory(DockWidgetFactoryBase):
    def __init__(self, id: str, position: DockWidgetFactoryBase.DockPosition, dockWidgetClass: type[QWidget]) -> None: ...

def __getattr__(name: str) -> Any: ...
