from typing import Literal
import numpy as np
import numpy.typing as npt
from PyQt6.QtGui import QImage

def raw_view(qimage: QImage) -> npt.NDArray[np.generic]: ...
def rgb_view(qimage: QImage, byteorder: Literal["big", "little"] = "big") -> npt.NDArray[np.uint8]: ...
def alpha_view(qimage: QImage) -> npt.NDArray[np.uint8]: ...
