[project]
name = "krita_comfyui"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pauan", email = "pauanyu+github@pm.me" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.5",
]

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"
